MAKE="make -C src/ KERNELDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C src/ clean"
BUILT_MODULE_NAME=hp-wmi
BUILT_MODULE_LOCATION=src/
DEST_MODULE_LOCATION=/kernel/drivers/platform/x86/hp/
PACKAGE_NAME=omen
PACKAGE_VERSION=0.6.2
AUTOINSTALL=yes
